sudo: false
language: node_js
node_js:
  - "0.12"
  - "4.2"
cache:
  directories:
    - node_modules
matrix:
  fast_finish: true
before_script:
  - npm install -g bower
  - bower install
after_success:
  - npm run coveralls
