sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "3"
  - "4"
cache:
  directories:
    - node_modules
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "3"
before_script:
  - npm install -g bower
  - bower install
after_success:
  - npm run coveralls
